name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # or whatever version you're using

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npx vite build

    - name: Debug - List all files
      run: |
        echo "Current directory structure (excluding node_modules):"
        find . -type d -name 'node_modules' -prune -o -print
        echo "------------------------"
        echo "Dist directory structure:"
        ls -R dist
        echo "------------------------"
        echo "Content of index.html:"
        cat dist/index.html
        echo "------------------------"


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist